"""Initial2

Revision ID: fb4d8a4faa06
Revises: 31a35a75f75c
Create Date: 2023-01-24 14:40:17.083037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4d8a4faa06'
down_revision = '31a35a75f75c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
